-- Artemis 数据持久化 Schema
-- 与 Java 版本完全兼容 (除 console 认证相关表外)

-- 1. 实例操作表 (instance)
CREATE TABLE IF NOT EXISTS instance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    INSTANCE_ID TEXT NOT NULL DEFAULT '',
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(INSTANCE_ID, SERVICE_ID, REGION_ID, OPERATION)
);

CREATE INDEX IF NOT EXISTS idx_instance_service ON instance(SERVICE_ID);
CREATE INDEX IF NOT EXISTS idx_instance_time ON instance(DataChange_LastTime);

-- 2. 实例日志表 (instance_log)
CREATE TABLE IF NOT EXISTS instance_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    INSTANCE_ID TEXT NOT NULL DEFAULT '',
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    COMPLETE INTEGER NOT NULL DEFAULT 0,
    EXTENSIONS TEXT NOT NULL DEFAULT '{}',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_instance_log_instance ON instance_log(INSTANCE_ID, SERVICE_ID, REGION_ID, OPERATION);
CREATE INDEX IF NOT EXISTS idx_instance_log_time ON instance_log(DataChange_LastTime);

-- 3. 服务器表 (server)
CREATE TABLE IF NOT EXISTS server (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(SERVER_ID, REGION_ID, OPERATION)
);

CREATE INDEX IF NOT EXISTS idx_server_region ON server(REGION_ID);
CREATE INDEX IF NOT EXISTS idx_server_time ON server(DataChange_LastTime);

-- 4. 服务器日志表 (server_log)
CREATE TABLE IF NOT EXISTS server_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    COMPLETE INTEGER NOT NULL DEFAULT 0,
    EXTENSIONS TEXT NOT NULL DEFAULT '{}',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_server_log_server ON server_log(SERVER_ID, REGION_ID, OPERATION);
CREATE INDEX IF NOT EXISTS idx_server_log_time ON server_log(DataChange_LastTime);

-- 5. 服务分组表 (service_group)
CREATE TABLE IF NOT EXISTS service_group (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    ZONE_ID TEXT NOT NULL DEFAULT '',
    NAME TEXT NOT NULL DEFAULT '',
    APP_ID TEXT NOT NULL DEFAULT '',
    DESCRIPTION TEXT,
    STATUS TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED INTEGER DEFAULT 0,
    type TEXT NOT NULL DEFAULT 'physical'
);

CREATE INDEX IF NOT EXISTS idx_group_service ON service_group(SERVICE_ID);
CREATE INDEX IF NOT EXISTS idx_group_status ON service_group(STATUS);
CREATE INDEX IF NOT EXISTS idx_group_deleted ON service_group(DELETED);
CREATE INDEX IF NOT EXISTS idx_group_time ON service_group(DataChange_LastTime);

-- 6. 分组标签表 (service_group_tag)
CREATE TABLE IF NOT EXISTS service_group_tag (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    TAG TEXT NOT NULL DEFAULT '',
    VALUE TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(GROUP_ID, TAG)
);

CREATE INDEX IF NOT EXISTS idx_group_tag_group ON service_group_tag(GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_group_tag_time ON service_group_tag(DataChange_LastTime);

-- 7. 分组标签日志表 (service_group_tag_log)
CREATE TABLE IF NOT EXISTS service_group_tag_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    TAG TEXT NOT NULL DEFAULT '',
    VALUE TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    EXTENSIONS TEXT NOT NULL DEFAULT '{}',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_tag_log_group ON service_group_tag_log(GROUP_ID, TAG);
CREATE INDEX IF NOT EXISTS idx_group_tag_log_operator ON service_group_tag_log(OPERATOR_ID);
CREATE INDEX IF NOT EXISTS idx_group_tag_log_time ON service_group_tag_log(DataChange_LastTime);

-- 8. 服务实例表 (service_instance)
CREATE TABLE IF NOT EXISTS service_instance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    INSTANCE_ID TEXT NOT NULL DEFAULT '',
    IP TEXT NOT NULL DEFAULT '',
    MACHINE_NAME TEXT NOT NULL DEFAULT '',
    METADATA TEXT NOT NULL DEFAULT '',
    PORT INTEGER NOT NULL DEFAULT 80,
    PROTOCOL TEXT NOT NULL DEFAULT 'http',
    REGION_ID TEXT NOT NULL DEFAULT '',
    ZONE_ID TEXT NOT NULL DEFAULT '',
    GROUP_ID TEXT NOT NULL DEFAULT '',
    HEALTHY_CHECK_URL TEXT NOT NULL DEFAULT '',
    URL TEXT NOT NULL DEFAULT '',
    DESCRIPTION TEXT,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(SERVICE_ID, INSTANCE_ID)
);

CREATE INDEX IF NOT EXISTS idx_service_inst_service ON service_instance(SERVICE_ID);
CREATE INDEX IF NOT EXISTS idx_service_inst_time ON service_instance(DataChange_LastTime);

-- 9. 服务实例日志表 (service_instance_log)
CREATE TABLE IF NOT EXISTS service_instance_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    INSTANCE_ID TEXT NOT NULL DEFAULT '',
    IP TEXT NOT NULL DEFAULT '',
    MACHINE_NAME TEXT NOT NULL DEFAULT '',
    METADATA TEXT NOT NULL DEFAULT '',
    PORT INTEGER NOT NULL DEFAULT 80,
    PROTOCOL TEXT NOT NULL DEFAULT 'http',
    REGION_ID TEXT NOT NULL DEFAULT '',
    ZONE_ID TEXT NOT NULL DEFAULT '',
    GROUP_ID TEXT NOT NULL DEFAULT '',
    HEALTHY_CHECK_URL TEXT NOT NULL DEFAULT '',
    URL TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_service_inst_log_instance ON service_instance_log(SERVICE_ID, INSTANCE_ID);
CREATE INDEX IF NOT EXISTS idx_service_inst_log_service ON service_instance_log(SERVICE_ID);
CREATE INDEX IF NOT EXISTS idx_service_inst_log_time ON service_instance_log(DataChange_LastTime);

-- 10. 路由规则表 (service_route_rule)
CREATE TABLE IF NOT EXISTS service_route_rule (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    NAME TEXT NOT NULL DEFAULT '',
    DESCRIPTION TEXT,
    STATUS TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED INTEGER DEFAULT 0,
    strategy TEXT NOT NULL DEFAULT 'weighted-round-robin'
);

CREATE INDEX IF NOT EXISTS idx_route_rule_service ON service_route_rule(SERVICE_ID);
CREATE INDEX IF NOT EXISTS idx_route_rule_status ON service_route_rule(STATUS);
CREATE INDEX IF NOT EXISTS idx_route_rule_deleted ON service_route_rule(DELETED);
CREATE INDEX IF NOT EXISTS idx_route_rule_time ON service_route_rule(DataChange_LastTime);

-- 11. 路由规则分组关联表 (service_route_rule_group)
CREATE TABLE IF NOT EXISTS service_route_rule_group (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ROUTE_RULE_ID INTEGER NOT NULL DEFAULT 0,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    WEIGHT INTEGER,
    UNRELEASED_WEIGHT INTEGER,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(ROUTE_RULE_ID, GROUP_ID)
);

CREATE INDEX IF NOT EXISTS idx_rule_group_rule ON service_route_rule_group(ROUTE_RULE_ID);
CREATE INDEX IF NOT EXISTS idx_rule_group_time ON service_route_rule_group(DataChange_LastTime);

-- 12. 路由规则日志表 (service_route_rule_log)
CREATE TABLE IF NOT EXISTS service_route_rule_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    NAME TEXT NOT NULL DEFAULT '',
    STATUS TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    EXTENSIONS TEXT NOT NULL DEFAULT '{}',
    REASON TEXT DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_route_rule_log_name ON service_route_rule_log(NAME, SERVICE_ID);
CREATE INDEX IF NOT EXISTS idx_route_rule_log_time ON service_route_rule_log(DataChange_LastTime);

-- 13. 路由规则分组日志表 (service_route_rule_group_log)
CREATE TABLE IF NOT EXISTS service_route_rule_group_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ROUTE_RULE_ID INTEGER NOT NULL DEFAULT 0,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    WEIGHT INTEGER,
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    EXTENSIONS TEXT NOT NULL DEFAULT '{}',
    REASON TEXT DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_route_rule_group_log_rule ON service_route_rule_group_log(ROUTE_RULE_ID, GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_route_rule_group_log_time ON service_route_rule_group_log(DataChange_LastTime);

-- 14. 分组实例关联表 (service_group_instance)
CREATE TABLE IF NOT EXISTS service_group_instance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    INSTANCE_ID TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(GROUP_ID, INSTANCE_ID)
);

CREATE INDEX IF NOT EXISTS idx_group_inst_group ON service_group_instance(GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_group_inst_time ON service_group_instance(DataChange_LastTime);

-- 15. 分组实例日志表 (service_group_instance_log)
CREATE TABLE IF NOT EXISTS service_group_instance_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    INSTANCE_ID TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    REASON TEXT DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_inst_log_group ON service_group_instance_log(GROUP_ID, INSTANCE_ID);
CREATE INDEX IF NOT EXISTS idx_group_inst_log_time ON service_group_instance_log(DataChange_LastTime);

-- 16. 分组操作表 (service_group_operation)
CREATE TABLE IF NOT EXISTS service_group_operation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    OPERATION TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(GROUP_ID, OPERATION)
);

CREATE INDEX IF NOT EXISTS idx_group_op_group ON service_group_operation(GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_group_op_time ON service_group_operation(DataChange_LastTime);

-- 17. 分组操作日志表 (service_group_operation_log)
CREATE TABLE IF NOT EXISTS service_group_operation_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    COMPLETE INTEGER NOT NULL DEFAULT 0,
    EXTENSIONS TEXT NOT NULL DEFAULT '{}',
    reason TEXT DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_op_log_group ON service_group_operation_log(GROUP_ID, OPERATION);
CREATE INDEX IF NOT EXISTS idx_group_op_log_operator ON service_group_operation_log(OPERATOR_ID);
CREATE INDEX IF NOT EXISTS idx_group_op_log_time ON service_group_operation_log(DataChange_LastTime);

-- 18. 分组日志表 (service_group_log)
CREATE TABLE IF NOT EXISTS service_group_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID INTEGER NOT NULL DEFAULT 0,
    PARENT_ID INTEGER NOT NULL DEFAULT 0,
    NAME TEXT NOT NULL DEFAULT '',
    STATUS TEXT NOT NULL DEFAULT '',
    WEIGHT INTEGER,
    TYPE TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    DESCRIPTION TEXT,
    TOKEN TEXT NOT NULL DEFAULT '',
    EXTENSIONS TEXT NOT NULL DEFAULT '{}',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    ZONE_ID TEXT NOT NULL DEFAULT '',
    APP_ID TEXT NOT NULL DEFAULT '',
    REASON TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_group_log_name_parent ON service_group_log(NAME, PARENT_ID);
CREATE INDEX IF NOT EXISTS idx_group_log_status ON service_group_log(STATUS);
CREATE INDEX IF NOT EXISTS idx_group_log_type ON service_group_log(TYPE);
CREATE INDEX IF NOT EXISTS idx_group_log_operator ON service_group_log(OPERATOR_ID);
CREATE INDEX IF NOT EXISTS idx_group_log_time ON service_group_log(DataChange_LastTime);

-- 19. Zone 表 (service_zone)
CREATE TABLE IF NOT EXISTS service_zone (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    ZONE_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(SERVICE_ID, REGION_ID, ZONE_ID, OPERATION)
);

CREATE INDEX IF NOT EXISTS idx_zone_service ON service_zone(SERVICE_ID);
CREATE INDEX IF NOT EXISTS idx_zone_time ON service_zone(DataChange_LastTime);

-- 20. Zone 日志表 (service_zone_log)
CREATE TABLE IF NOT EXISTS service_zone_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_ID TEXT NOT NULL DEFAULT '',
    ZONE_ID TEXT NOT NULL DEFAULT '',
    REGION_ID TEXT NOT NULL DEFAULT '',
    OPERATION TEXT NOT NULL DEFAULT '',
    OPERATOR_ID TEXT NOT NULL DEFAULT '',
    TOKEN TEXT NOT NULL DEFAULT '',
    REASON TEXT DEFAULT '',
    COMPLETE INTEGER NOT NULL DEFAULT 0,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataChange_LastTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_zone_log_service ON service_zone_log(SERVICE_ID, REGION_ID, ZONE_ID, OPERATION);
CREATE INDEX IF NOT EXISTS idx_zone_log_time ON service_zone_log(DataChange_LastTime);

-- 21. 金丝雀配置表 (canary_config) - Rust 特有
CREATE TABLE IF NOT EXISTS canary_config (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_id TEXT NOT NULL UNIQUE,
    ip_whitelist TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_canary_service ON canary_config(service_id);
CREATE INDEX IF NOT EXISTS idx_canary_enabled ON canary_config(enabled);

-- 22. 操作审计日志表 (audit_log) - Rust 特有
CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    log_id BIGINT NOT NULL UNIQUE,
    operation_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    operator_id TEXT NOT NULL,
    operation_time BIGINT NOT NULL,
    details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_type ON audit_log(operation_type);
CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_log(target_id);
CREATE INDEX IF NOT EXISTS idx_audit_operator ON audit_log(operator_id);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_log(operation_time);

-- 23. 用户表 (auth_users) - Console 认证系统
CREATE TABLE IF NOT EXISTS auth_users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    email TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin', 'operator', 'viewer')),
    status TEXT NOT NULL CHECK(status IN ('active', 'inactive')),
    description TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_username ON auth_users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON auth_users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON auth_users(status);

-- 24. 会话表 (auth_sessions) - Console 认证系统
CREATE TABLE IF NOT EXISTS auth_sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL,
    token TEXT NOT NULL UNIQUE,
    ip_address TEXT,
    user_agent TEXT,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    last_activity BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON auth_sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON auth_sessions(expires_at);

-- 25. 登录历史表 (auth_login_history) - Console 认证系统
CREATE TABLE IF NOT EXISTS auth_login_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    login_time BIGINT NOT NULL,
    ip_address TEXT NOT NULL,
    user_agent TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('success', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_login_history_user ON auth_login_history(user_id);
CREATE INDEX IF NOT EXISTS idx_login_history_time ON auth_login_history(login_time);
CREATE INDEX IF NOT EXISTS idx_login_history_status ON auth_login_history(status);
